# Generated by Django 5.0.6 on 2024-06-14 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0004_alter_estado_id_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id_comida', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('store', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='comida_images/')),
                ('proximity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField()),
                ('starts', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado.estado')),
            ],
        ),
    ]
