# Generated by Django 5.0.6 on 2024-06-13 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0003_remove_estado_id_estado_id_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_cliente', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('num_tel', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado.estado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
