# Generated by Django 5.0.6 on 2024-06-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_cliente_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_staff',
        ),
    ]
