# Generated by Django 5.0.6 on 2024-07-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_cliente_nombre_completo_alter_cliente_num_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(default='default_password', max_length=255),
        ),
    ]
