# Generated by Django 5.0.6 on 2024-07-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_cliente_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(max_length=255),
        ),
    ]
