# Generated by Django 5.0.6 on 2024-06-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='id',
        ),
        migrations.AddField(
            model_name='like',
            name='id_like',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
