# Generated by Django 5.0.6 on 2024-06-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_remove_like_id_like_id_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id_like',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
