# Generated by Django 5.0.6 on 2024-06-14 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comida', '0001_initial'),
        ('estado', '0004_alter_estado_id_estado'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id_pedido_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_comida', models.IntegerField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.comida')),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado.estado')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedido.pedido')),
            ],
        ),
    ]
