# Generated by Django 5.0.6 on 2024-06-14 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0004_alter_estado_id_estado'),
        ('usuario', '0003_remove_cliente_is_active_remove_cliente_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='usuario.cliente')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.estado')),
            ],
        ),
    ]
